// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package location

import (
	"context"

	"github.com/ocenb/geo-alerts/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocationRepo creates a new instance of MockLocationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepo {
	mock := &MockLocationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocationRepo is an autogenerated mock type for the LocationRepo type
type MockLocationRepo struct {
	mock.Mock
}

type MockLocationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepo) EXPECT() *MockLocationRepo_Expecter {
	return &MockLocationRepo_Expecter{mock: &_m.Mock}
}

// SaveCheckLog provides a mock function for the type MockLocationRepo
func (_mock *MockLocationRepo) SaveCheckLog(ctx context.Context, check *models.CheckLocationResult) error {
	ret := _mock.Called(ctx, check)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CheckLocationResult) error); ok {
		r0 = returnFunc(ctx, check)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocationRepo_SaveCheckLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckLog'
type MockLocationRepo_SaveCheckLog_Call struct {
	*mock.Call
}

// SaveCheckLog is a helper method to define mock.On call
//   - ctx context.Context
//   - check *models.CheckLocationResult
func (_e *MockLocationRepo_Expecter) SaveCheckLog(ctx interface{}, check interface{}) *MockLocationRepo_SaveCheckLog_Call {
	return &MockLocationRepo_SaveCheckLog_Call{Call: _e.mock.On("SaveCheckLog", ctx, check)}
}

func (_c *MockLocationRepo_SaveCheckLog_Call) Run(run func(ctx context.Context, check *models.CheckLocationResult)) *MockLocationRepo_SaveCheckLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.CheckLocationResult
		if args[1] != nil {
			arg1 = args[1].(*models.CheckLocationResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocationRepo_SaveCheckLog_Call) Return(err error) *MockLocationRepo_SaveCheckLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocationRepo_SaveCheckLog_Call) RunAndReturn(run func(ctx context.Context, check *models.CheckLocationResult) error) *MockLocationRepo_SaveCheckLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncidentRepo creates a new instance of MockIncidentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncidentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncidentRepo {
	mock := &MockIncidentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncidentRepo is an autogenerated mock type for the IncidentRepo type
type MockIncidentRepo struct {
	mock.Mock
}

type MockIncidentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncidentRepo) EXPECT() *MockIncidentRepo_Expecter {
	return &MockIncidentRepo_Expecter{mock: &_m.Mock}
}

// GetActive provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) GetActive(ctx context.Context) ([]models.IncidentShort, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 []models.IncidentShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.IncidentShort, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.IncidentShort); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IncidentShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type MockIncidentRepo_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIncidentRepo_Expecter) GetActive(ctx interface{}) *MockIncidentRepo_GetActive_Call {
	return &MockIncidentRepo_GetActive_Call{Call: _e.mock.On("GetActive", ctx)}
}

func (_c *MockIncidentRepo_GetActive_Call) Run(run func(ctx context.Context)) *MockIncidentRepo_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_GetActive_Call) Return(incidentShorts []models.IncidentShort, err error) *MockIncidentRepo_GetActive_Call {
	_c.Call.Return(incidentShorts, err)
	return _c
}

func (_c *MockIncidentRepo_GetActive_Call) RunAndReturn(run func(ctx context.Context) ([]models.IncidentShort, error)) *MockIncidentRepo_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheRepo creates a new instance of MockCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepo {
	mock := &MockCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepo is an autogenerated mock type for the CacheRepo type
type MockCacheRepo struct {
	mock.Mock
}

type MockCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepo) EXPECT() *MockCacheRepo_Expecter {
	return &MockCacheRepo_Expecter{mock: &_m.Mock}
}

// GetActiveIncidents provides a mock function for the type MockCacheRepo
func (_mock *MockCacheRepo) GetActiveIncidents(ctx context.Context) ([]models.IncidentShort, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveIncidents")
	}

	var r0 []models.IncidentShort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.IncidentShort, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.IncidentShort); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IncidentShort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepo_GetActiveIncidents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveIncidents'
type MockCacheRepo_GetActiveIncidents_Call struct {
	*mock.Call
}

// GetActiveIncidents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheRepo_Expecter) GetActiveIncidents(ctx interface{}) *MockCacheRepo_GetActiveIncidents_Call {
	return &MockCacheRepo_GetActiveIncidents_Call{Call: _e.mock.On("GetActiveIncidents", ctx)}
}

func (_c *MockCacheRepo_GetActiveIncidents_Call) Run(run func(ctx context.Context)) *MockCacheRepo_GetActiveIncidents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheRepo_GetActiveIncidents_Call) Return(incidentShorts []models.IncidentShort, err error) *MockCacheRepo_GetActiveIncidents_Call {
	_c.Call.Return(incidentShorts, err)
	return _c
}

func (_c *MockCacheRepo_GetActiveIncidents_Call) RunAndReturn(run func(ctx context.Context) ([]models.IncidentShort, error)) *MockCacheRepo_GetActiveIncidents_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveIncidents provides a mock function for the type MockCacheRepo
func (_mock *MockCacheRepo) SetActiveIncidents(ctx context.Context, incidents []models.IncidentShort) error {
	ret := _mock.Called(ctx, incidents)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveIncidents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.IncidentShort) error); ok {
		r0 = returnFunc(ctx, incidents)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepo_SetActiveIncidents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveIncidents'
type MockCacheRepo_SetActiveIncidents_Call struct {
	*mock.Call
}

// SetActiveIncidents is a helper method to define mock.On call
//   - ctx context.Context
//   - incidents []models.IncidentShort
func (_e *MockCacheRepo_Expecter) SetActiveIncidents(ctx interface{}, incidents interface{}) *MockCacheRepo_SetActiveIncidents_Call {
	return &MockCacheRepo_SetActiveIncidents_Call{Call: _e.mock.On("SetActiveIncidents", ctx, incidents)}
}

func (_c *MockCacheRepo_SetActiveIncidents_Call) Run(run func(ctx context.Context, incidents []models.IncidentShort)) *MockCacheRepo_SetActiveIncidents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.IncidentShort
		if args[1] != nil {
			arg1 = args[1].([]models.IncidentShort)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepo_SetActiveIncidents_Call) Return(err error) *MockCacheRepo_SetActiveIncidents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepo_SetActiveIncidents_Call) RunAndReturn(run func(ctx context.Context, incidents []models.IncidentShort) error) *MockCacheRepo_SetActiveIncidents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueProducer creates a new instance of MockQueueProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueProducer {
	mock := &MockQueueProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueProducer is an autogenerated mock type for the QueueProducer type
type MockQueueProducer struct {
	mock.Mock
}

type MockQueueProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueProducer) EXPECT() *MockQueueProducer_Expecter {
	return &MockQueueProducer_Expecter{mock: &_m.Mock}
}

// EnqueueDangerAlert provides a mock function for the type MockQueueProducer
func (_mock *MockQueueProducer) EnqueueDangerAlert(ctx context.Context, userID string, latitude float64, longitude float64) error {
	ret := _mock.Called(ctx, userID, latitude, longitude)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueDangerAlert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, float64) error); ok {
		r0 = returnFunc(ctx, userID, latitude, longitude)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueProducer_EnqueueDangerAlert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDangerAlert'
type MockQueueProducer_EnqueueDangerAlert_Call struct {
	*mock.Call
}

// EnqueueDangerAlert is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - latitude float64
//   - longitude float64
func (_e *MockQueueProducer_Expecter) EnqueueDangerAlert(ctx interface{}, userID interface{}, latitude interface{}, longitude interface{}) *MockQueueProducer_EnqueueDangerAlert_Call {
	return &MockQueueProducer_EnqueueDangerAlert_Call{Call: _e.mock.On("EnqueueDangerAlert", ctx, userID, latitude, longitude)}
}

func (_c *MockQueueProducer_EnqueueDangerAlert_Call) Run(run func(ctx context.Context, userID string, latitude float64, longitude float64)) *MockQueueProducer_EnqueueDangerAlert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueProducer_EnqueueDangerAlert_Call) Return(err error) *MockQueueProducer_EnqueueDangerAlert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueProducer_EnqueueDangerAlert_Call) RunAndReturn(run func(ctx context.Context, userID string, latitude float64, longitude float64) error) *MockQueueProducer_EnqueueDangerAlert_Call {
	_c.Call.Return(run)
	return _c
}
