// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package incident

import (
	"context"
	"time"

	"github.com/ocenb/geo-alerts/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIncidentRepo creates a new instance of MockIncidentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncidentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncidentRepo {
	mock := &MockIncidentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncidentRepo is an autogenerated mock type for the IncidentRepo type
type MockIncidentRepo struct {
	mock.Mock
}

type MockIncidentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncidentRepo) EXPECT() *MockIncidentRepo_Expecter {
	return &MockIncidentRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) Create(ctx context.Context, params *models.CreateIncidentParams) (*models.Incident, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Incident
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateIncidentParams) (*models.Incident, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateIncidentParams) *models.Incident); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Incident)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.CreateIncidentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIncidentRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - params *models.CreateIncidentParams
func (_e *MockIncidentRepo_Expecter) Create(ctx interface{}, params interface{}) *MockIncidentRepo_Create_Call {
	return &MockIncidentRepo_Create_Call{Call: _e.mock.On("Create", ctx, params)}
}

func (_c *MockIncidentRepo_Create_Call) Run(run func(ctx context.Context, params *models.CreateIncidentParams)) *MockIncidentRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.CreateIncidentParams
		if args[1] != nil {
			arg1 = args[1].(*models.CreateIncidentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_Create_Call) Return(incident *models.Incident, err error) *MockIncidentRepo_Create_Call {
	_c.Call.Return(incident, err)
	return _c
}

func (_c *MockIncidentRepo_Create_Call) RunAndReturn(run func(ctx context.Context, params *models.CreateIncidentParams) (*models.Incident, error)) *MockIncidentRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) Deactivate(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncidentRepo_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockIncidentRepo_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIncidentRepo_Expecter) Deactivate(ctx interface{}, id interface{}) *MockIncidentRepo_Deactivate_Call {
	return &MockIncidentRepo_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockIncidentRepo_Deactivate_Call) Run(run func(ctx context.Context, id int64)) *MockIncidentRepo_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_Deactivate_Call) Return(err error) *MockIncidentRepo_Deactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncidentRepo_Deactivate_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockIncidentRepo_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) GetByID(ctx context.Context, id int64) (*models.Incident, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Incident
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.Incident, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.Incident); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Incident)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIncidentRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockIncidentRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockIncidentRepo_GetByID_Call {
	return &MockIncidentRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIncidentRepo_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockIncidentRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_GetByID_Call) Return(incident *models.Incident, err error) *MockIncidentRepo_GetByID_Call {
	_c.Call.Return(incident, err)
	return _c
}

func (_c *MockIncidentRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*models.Incident, error)) *MockIncidentRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) GetStats(ctx context.Context, window time.Duration) ([]models.Stats, error) {
	ret := _mock.Called(ctx, window)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 []models.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) ([]models.Stats, error)); ok {
		return returnFunc(ctx, window)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) []models.Stats); ok {
		r0 = returnFunc(ctx, window)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Stats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, window)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockIncidentRepo_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - window time.Duration
func (_e *MockIncidentRepo_Expecter) GetStats(ctx interface{}, window interface{}) *MockIncidentRepo_GetStats_Call {
	return &MockIncidentRepo_GetStats_Call{Call: _e.mock.On("GetStats", ctx, window)}
}

func (_c *MockIncidentRepo_GetStats_Call) Run(run func(ctx context.Context, window time.Duration)) *MockIncidentRepo_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_GetStats_Call) Return(statss []models.Stats, err error) *MockIncidentRepo_GetStats_Call {
	_c.Call.Return(statss, err)
	return _c
}

func (_c *MockIncidentRepo_GetStats_Call) RunAndReturn(run func(ctx context.Context, window time.Duration) ([]models.Stats, error)) *MockIncidentRepo_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) List(ctx context.Context, limit int, offset int) ([]models.Incident, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Incident
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Incident, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []models.Incident); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Incident)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIncidentRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockIncidentRepo_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockIncidentRepo_List_Call {
	return &MockIncidentRepo_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockIncidentRepo_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockIncidentRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_List_Call) Return(incidents []models.Incident, err error) *MockIncidentRepo_List_Call {
	_c.Call.Return(incidents, err)
	return _c
}

func (_c *MockIncidentRepo_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]models.Incident, error)) *MockIncidentRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIncidentRepo
func (_mock *MockIncidentRepo) Update(ctx context.Context, params *models.UpdateIncidentParams) (*models.Incident, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Incident
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateIncidentParams) (*models.Incident, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateIncidentParams) *models.Incident); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Incident)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UpdateIncidentParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIncidentRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIncidentRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - params *models.UpdateIncidentParams
func (_e *MockIncidentRepo_Expecter) Update(ctx interface{}, params interface{}) *MockIncidentRepo_Update_Call {
	return &MockIncidentRepo_Update_Call{Call: _e.mock.On("Update", ctx, params)}
}

func (_c *MockIncidentRepo_Update_Call) Run(run func(ctx context.Context, params *models.UpdateIncidentParams)) *MockIncidentRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UpdateIncidentParams
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateIncidentParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncidentRepo_Update_Call) Return(incident *models.Incident, err error) *MockIncidentRepo_Update_Call {
	_c.Call.Return(incident, err)
	return _c
}

func (_c *MockIncidentRepo_Update_Call) RunAndReturn(run func(ctx context.Context, params *models.UpdateIncidentParams) (*models.Incident, error)) *MockIncidentRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheRepo creates a new instance of MockCacheRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepo {
	mock := &MockCacheRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepo is an autogenerated mock type for the CacheRepo type
type MockCacheRepo struct {
	mock.Mock
}

type MockCacheRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepo) EXPECT() *MockCacheRepo_Expecter {
	return &MockCacheRepo_Expecter{mock: &_m.Mock}
}

// InvalidateActiveIncidents provides a mock function for the type MockCacheRepo
func (_mock *MockCacheRepo) InvalidateActiveIncidents(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateActiveIncidents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepo_InvalidateActiveIncidents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateActiveIncidents'
type MockCacheRepo_InvalidateActiveIncidents_Call struct {
	*mock.Call
}

// InvalidateActiveIncidents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheRepo_Expecter) InvalidateActiveIncidents(ctx interface{}) *MockCacheRepo_InvalidateActiveIncidents_Call {
	return &MockCacheRepo_InvalidateActiveIncidents_Call{Call: _e.mock.On("InvalidateActiveIncidents", ctx)}
}

func (_c *MockCacheRepo_InvalidateActiveIncidents_Call) Run(run func(ctx context.Context)) *MockCacheRepo_InvalidateActiveIncidents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheRepo_InvalidateActiveIncidents_Call) Return(err error) *MockCacheRepo_InvalidateActiveIncidents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepo_InvalidateActiveIncidents_Call) RunAndReturn(run func(ctx context.Context) error) *MockCacheRepo_InvalidateActiveIncidents_Call {
	_c.Call.Return(run)
	return _c
}
